version: '3.1'

services:

  caddy:
    image: abiosoft/caddy
    restart: always
    environment:
      ACME_AGREE: "true"
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./log/caddy:/var/log/caddy

  v2ray:
    image: v2ray/official
    container_name: v2ray
    volumes:
      - ./config.json:/etc/v2ray/config.json
      - ./log/v2ray:/var/log/v2ray
    # expose:
    #   - "8082"